spring:
  application:
    name: todo-list

  datasource:
    url: jdbc:postgresql://localhost:5433/todolist
    driver-class-name: org.postgresql.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    deferred-initialization: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    redis:
      time-to-live: 10m

api:
  security:
    token:
      secret: "!321-security-key-token-123@"